replace offset args with new GinkgoHelper
kubernetes-csi/csi-test pull request #523
Opened 2024-04-02 12:42 UTC by huww98

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug

/kind cleanup

> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

it is simpler, and easier to maintain

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

2024-04-16 12:17 UTC, pohly requested changes
`ginkgo.GinkgoHelper` didn't exist when this code was written. Using it indeed is simpler.

We want to treat all methods as helpers, right? Then some `ginkgo.GinkgoHelper` calls are missing.

2024-04-16 12:17 UTC, pohly commented on pkg/sanity/resources.go
> +	Expect(id).NotTo(BeEmpty(), "volume ID is empty")
Missing `ginkgo.GinkgoHelper` here.

2024-04-16 12:17 UTC, pohly commented on pkg/sanity/resources.go
> +	Expect(id).NotTo(BeEmpty(), "ID for register snapshot is missing")
Missing `ginkgo.GinkgoHelper` here.

2024-04-16 12:17 UTC, pohly commented on pkg/sanity/resources.go
> +	Expect(id).NotTo(BeEmpty(), "ID for unregister resource is missing")
Missing `ginkgo.GinkgoHelper` here.

2024-04-16 12:38 UTC, huww98 commented
> We want to treat all methods as helpers, right?

Yes, but so long as one of the callers has `GinkgoHelper()`, it should be fine. And I think `registerXxx()` is not intended to be called outside of resources.go.

2024-04-16 13:49 UTC, pohly commented
> Yes, but so long as one of the callers has GinkgoHelper(), it should be fine.

That's not my understanding of how that function works. [GinkgoHelper](https://pkg.go.dev/github.com/onsi/ginkgo/v2#GinkgoHelper) marks "*the function* it's called in as a test helper" (emphasis mine). It does not mark the function and all functions called by it as helper.

2024-04-17 07:18 UTC, pohly commented
/ok-to-test

2024-04-17 07:54 UTC, pohly commented
/lgtm
/approve

2024-04-17 07:58 UTC, merged